services:
  - type: web
    name: portafolio-mejia-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/system/stats
    envVars:
      - key: NODE_ENV
        value: production
